languageCode = "en-us"
title = "Andre Scott's Portfolio"
theme = "hugo-acs-portfolio-theme"
themesdir = "./themes/"
copyright = "André Casey Scott ©"


[params]
  name = "André Casey Scott"
  description = "A collection of website design, graphic design, and marketing projects."
  initials = "ACS"
  googleAnalytics = ""

  [[params.social]]
    name = "LinkedIn"
    link = "https://linkedin.com/in/andrecaseyscott"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'writing_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[module]
  [module.hugoVersion]
    min = "0.81.0"
    max = "0.84.2"

    